# Generated by Django 6.0.2 on 2026-03-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='blanks_reserved_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='change_type',
            field=models.CharField(choices=[('PO_RECEIVED', 'PO Received'), ('PRODUCTION_USED', 'Production Used'), ('PRODUCTION_CREATED', 'Production Created'), ('DISPATCHED', 'Dispatched'), ('ADJUSTMENT', 'Adjustment'), ('RESERVATION_ADJUSTMENT', 'Reservation Adjustment')], max_length=32),
        ),
    ]
