# Generated by Django 6.0.2 on 2026-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory_blanks_reserved_qty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='blanks_qty',
            new_name='finished_blanks',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='blanks_reserved_qty',
            new_name='total_blanks',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='finished_qty',
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='change_type',
            field=models.CharField(choices=[('PO_RECEIVED', 'PO Received'), ('PRODUCTION_USED', 'Production Used'), ('PRODUCTION_CREATED', 'Production Created'), ('DISPATCHED', 'Dispatched'), ('ADJUSTMENT', 'Adjustment')], max_length=32),
        ),
    ]
