# Generated by Django 6.0.2 on 2026-04-26 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_machine_operator'),
        ('inventory', '0004_stockreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name_plural': 'Inventories'},
        ),
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='quantity_changed',
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Positive for increase, negative for decrease.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.company'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='finished_blanks',
            field=models.PositiveIntegerField(default=0, help_text='Total finished parts in stock.'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.part'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_blanks',
            field=models.PositiveIntegerField(default=0, help_text='Total raw blanks in stock.'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='change_type',
            field=models.CharField(choices=[('PO_RECEIVED', 'PO Received'), ('PRODUCTION_USED', 'Production Used'), ('PRODUCTION_CREATED', 'Production Created'), ('DISPATCHED', 'Dispatched'), ('SALES_OUT', 'Sales Out'), ('ADJUSTMENT', 'Adjustment')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stockreceipt',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
