# Generated by Django 6.0.4 on 2026-06-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_options_alter_inventorylog_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventory Log', 'verbose_name_plural': 'Inventory Logs'},
        ),
    ]
