# Generated by Django 6.0.2 on 2026-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='last_edit_reason',
            field=models.TextField(blank=True, help_text='Reason for the last edit.', null=True),
        ),
    ]
