# Generated by Django 6.0.2 on 2026-03-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0002_customerorder_last_edit_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft deletion flag.'),
        ),
    ]
