# Generated by Django 6.0.2 on 2026-03-08 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0003_customerorder_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='The user who last edited this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_customer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
