# Generated by Django 6.0.2 on 2026-04-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0004_customerorder_last_edited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('IN_PRODUCTION', 'In production'), ('READY_FOR_DISPATCH', 'Ready for dispatch'), ('PARTIALLY_SHIPPED', 'Partially shipped'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], default='DRAFT', max_length=32),
        ),
    ]
