# Generated by Django 6.0.2 on 2026-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0005_alter_customerorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='qc_report',
            field=models.FileField(blank=True, null=True, upload_to='qc_reports/'),
        ),
    ]
