# Generated by Django 6.0.2 on 2026-06-16 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0006_customerorder_qc_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='po_date',
            field=models.DateField(default=datetime.date.today, help_text='The actual date of the purchase order.'),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='po_number',
            field=models.CharField(help_text='Purchase order number entered manually by the user.', max_length=50),
        ),
    ]
