# Generated by Django 6.0.4 on 2026-06-24 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0007_customerorder_po_date_alter_customerorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='po_date',
            field=models.DateField(default=datetime.date.today, help_text='The officially registered order date.'),
        ),
    ]
