# Generated by Django 6.0.4 on 2026-06-25 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0008_alter_customerorder_po_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255)),
                ('part_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('IN_PRODUCTION', 'In production'), ('READY_FOR_DISPATCH', 'Ready for dispatch'), ('PARTIALLY_SHIPPED', 'Partially shipped'), ('DISPATCHED', 'Dispatched'), ('CLOSED', 'Closed')], default='DRAFT', max_length=32)),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('EDITED', 'Edited'), ('STATUS_CHANGED', 'Status Changed'), ('SOFT_DELETED', 'Soft Deleted')], max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_order_logs', to=settings.AUTH_USER_MODEL)),
                ('customer_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='customer_order.customerorder')),
            ],
            options={
                'verbose_name': 'Customer Order Log',
                'verbose_name_plural': 'Customer Order Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
