# Generated by Django 6.0.2 on 2026-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0009_customerorderlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='is_short_closed',
            field=models.BooleanField(default=False, help_text='Marked as short-closed: no further shipments will be accepted.'),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='shipped_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Total quantity shipped so far.'),
        ),
    ]
