# Generated by Django 6.0.4 on 2026-08-03

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0010_customerorder_is_short_closed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='qc_report',
            field=models.FileField(blank=True, null=True, storage=core.storage.DocumentStorage(), upload_to='qc_reports/'),
        ),
    ]
