# Generated by Django 6.0.2 on 2026-04-26 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='shipped_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
