# Generated by Django 6.0.2 on 2026-04-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0005_alter_customerorder_status'),
        ('dispatch', '0002_dispatchrecord_shipped_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchrecord',
            name='is_short_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_records', to='customer_order.customerorder'),
        ),
        migrations.AlterField(
            model_name='dispatchrecord',
            name='shipped_quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
