# Generated by Django 6.0.2 on 2026-04-26 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0006_customerorder_qc_report'),
        ('dispatch', '0003_dispatchrecord_is_short_closed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('part_name', models.CharField(max_length=255)),
                ('shipped_quantity', models.PositiveIntegerField()),
                ('qc_report', models.FileField(upload_to='qc_reports/')),
                ('is_short_closed', models.BooleanField(default=False)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_history_entries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_history', to='customer_order.customerorder')),
            ],
            options={
                'verbose_name_plural': 'Dispatch Histories',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.DeleteModel(
            name='DispatchRecord',
        ),
    ]
