# Generated by Django 6.0.2 on 2026-05-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0006_customerorder_qc_report'),
        ('dispatch', '0004_dispatchhistory_delete_dispatchrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Dispatch (Ready/Partial)',
                'verbose_name_plural': 'Dispatch (Ready/Partial)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customer_order.customerorder',),
        ),
    ]
