# Generated by Django 6.0.2 on 2026-08-02 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0005_dispatchorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchhistory',
            name='actual_shipped_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='has_supplementary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='main_invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='dispatch_invoices/'),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='main_qc_report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='qc_reports/'),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='ordered_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='parent_dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplementary_dispatches', to='dispatch.dispatchhistory'),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='supplementary_invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='dispatch_invoices/'),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='supplementary_qc_report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='qc_reports/'),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='supplementary_shipped_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dispatchhistory',
            name='qc_report',
            field=models.FileField(blank=True, null=True, upload_to='qc_reports/'),
        ),
    ]
