# Generated by Django 6.0.4 on 2026-08-03

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_dispatchhistory_actual_shipped_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchhistory',
            name='main_invoice_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage.DocumentStorage(), upload_to='dispatch_invoices/'),
        ),
        migrations.AlterField(
            model_name='dispatchhistory',
            name='main_qc_report_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage.DocumentStorage(), upload_to='qc_reports/'),
        ),
        migrations.AlterField(
            model_name='dispatchhistory',
            name='qc_report',
            field=models.FileField(blank=True, null=True, storage=core.storage.DocumentStorage(), upload_to='qc_reports/'),
        ),
        migrations.AlterField(
            model_name='dispatchhistory',
            name='supplementary_invoice_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage.DocumentStorage(), upload_to='dispatch_invoices/'),
        ),
        migrations.AlterField(
            model_name='dispatchhistory',
            name='supplementary_qc_report_pdf',
            field=models.FileField(blank=True, null=True, storage=core.storage.DocumentStorage(), upload_to='qc_reports/'),
        ),
    ]
