# Generated by Django 5.2.10 on 2026-01-07 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatched', models.BooleanField(default=False)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchase_orders.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='QCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='qc_reports/')),
                ('status', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('po', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='purchase_orders.purchaseorder')),
            ],
        ),
    ]
