# Generated by Django 6.0.2 on 2026-03-17 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_order', '0004_customerorder_last_edited_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255)),
                ('operator_name', models.CharField(max_length=255)),
                ('deadline', models.DateField(help_text='Target completion date')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20)),
                ('required_quantity', models.PositiveIntegerField()),
                ('produced_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('operator_working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parts_made_in_working_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('operator_overtime_hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('parts_made_in_overtime', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('idle_time_hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
                ('idle_reason', models.TextField(blank=True, help_text='Mandatory if idle_time_hours > 0', null=True)),
                ('job_rating', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('VERY_GOOD', 'Very Good'), ('GOOD', 'Good'), ('POOR', 'Poor')], max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Mandatory if job rating is less than Excellent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_reports', to=settings.AUTH_USER_MODEL)),
                ('customer_order', models.OneToOneField(help_text='The approved customer order this report belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='production_report', to='customer_order.customerorder')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_production_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
