# Generated by Django 6.0.2 on 2026-03-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='scrap_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
