# Generated by Django 6.0.2 on 2026-05-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_order', '0006_customerorder_qc_report'),
        ('production', '0002_productionreport_scrap_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Production (Approved/In-Progress)',
                'verbose_name_plural': 'Production (Approved/In-Progress)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customer_order.customerorder',),
        ),
    ]
