# Generated by Django 6.0.2 on 2026-07-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='entry_logs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
