# Generated by Django 5.2.10 on 2026-01-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PRODUCTION', 'In Production'), ('QC', 'QC'), ('DISPATCHED', 'Dispatched')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.part')),
            ],
        ),
    ]
