# Generated by Django 5.2.10 on 2026-02-11 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_part_created_at_part_description_part_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
        migrations.RemoveField(
            model_name='part',
            name='updated_at',
        ),
    ]
