# Generated by Django 6.0.2 on 2026-06-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_machine_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='part',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='parts/'),
        ),
    ]
