# Generated by Django 5.2.10 on 2026-02-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_part_created_at_remove_part_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
