# Generated by Django 5.2.10 on 2026-02-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_part_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='description',
        ),
    ]
