# Generated by Django 6.0.2 on 2026-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_part_description_part_image'),
    ]

    operations = [
    ]
