# Generated by Django 6.0.4 on 2026-06-25 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_companies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='image',
        ),
    ]
